name: Nix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  choose-runner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.runner.outputs.runner }}

    steps:
    - id: runner
      run: |
        if [ "${{ github.actor }}" == "herabel" ]; then
          echo "runner=self-hosted" >> "$GITHUB_OUTPUT"   
        else
         echo "runner=ubuntu-latest" >> "$GITHUB_OUTPUT"
        fi

  build:

    needs: choose-runner

    runs-on: ${{ needs.choose-runner.outputs.runner }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v12

    - name: Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v8

    - name: Check Nix Flake and build
      run: |
          nix flake check --all-systems --impure
          nix develop --command cargo test --release
